package com.japnoor.anticorruption

data class Complaints(var complaintDept : String="",
                      var complaintLoc : String="",
                      var complaintCategory : String="",
                      var complaintAgainst : String="",
                      var complaintDetails : String="",
                      var complaintDistrict : String="",
                      var userId:String="",
                      var complaintDate:String="",
                      var complaintId : String="",
                      var audioName : String="",
                      var audioUrl : String="",
                      var videoName : String="",
                      var videoUrl : String="",
                      var userName : String="",
                      var userEmail : String="",
                      var userOldEmail : String="",
                      var status : String="",
                      var complaintNumber : String="",
                      var complaintTime : String="",
                      var statusDescription: String = "",
                      var imageName : String="",
                      var imageUrl : String=""
)
